#!/usr/bin/env bash
# displays "Best School" 10x with "Hi" in the 9th line

count=1
while [[ ${count} -le 11 ]]; do
    if [[ ${count} -eq 10 ]]; then
    echo "Hi"
else
    echo "Best School"
    fi
    
done 