#!/usr/bin/env bash
# display 10x a given string, and different string on the $th and 8th line.

count=1
while [[ ${count} -le 10 ]]; do
    if [[ ${count} -eq 4 ]]; then
        echo "bad luck"
    elif [[ ${count} -eq 8 ]]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
    