#!/usr/bin/env bash
# display number 1 - 20, with a given string on 4, 9, and 17.

count=1
while [[ ${count} -le 20 ]]; do
    case "${count}" in
        "4") echo "bad luck from China"
        ;;
        "9") echo "bad luck from Japan"
        ;;
        "17") echo "bad luck from Italy"
        ;;
        *)
         echo "${count}"
    esac
    ((count++))
done
